[package]
name = "rut"
version = "0.1.0"
edition = "2024"
autoexamples = false

[[example]]
name = "declarative"
path = "examples/declarative.rs"

[[example]]
name = "parallel"
path = "examples/parallel.rs"

[[example]]
name = "sequential"
path = "examples/sequential.rs"

[dependencies]
anyhow = "1"
tokio = { version = "*", features = ["full"] }
async-trait = "*"
chrono = { version = "*", features = ["serde"] }
num_cpus = "*"
rand = "*"
rut-macros = { path = "../rut-macros" }
quick-xml = "0.38"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[lib]
name = "rut"
path = "src/lib.rs"

[dev-dependencies]
trybuild = "*"
tempfile = "3"
